name: Python SonarQube Analysis

on:
  push:
    branches: ["main", "development"]
  pull_request:
    branches: ["main", "development"]

jobs:
  sonar-analysis:
    name: Analyze Python Project with SonarCloud
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Install SonarScanner
      run: |
        # Download and install SonarScanner
        wget https://github.com/SonarSource/sonar-scanner-cli/releases/download/4.7.0.2747/sonar-scanner-4.7.0.2747-linux.zip
        unzip sonar-scanner-4.7.0.2747-linux.zip
        sudo mv sonar-scanner-4.7.0.2747-linux /opt/sonar-scanner
        sudo ln -s /opt/sonar-scanner/bin/sonar-scanner /usr/local/bin/sonar-scanner

    - name: Set up SonarCloud
      uses: SonarSource/sonarcloud-github-action@v3
      with:
        organization: 'snacktechteam'
        projectKey: 'SnackTechTeam_snacktech-lambda-authorizer'
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Run SonarCloud Analysis
      run: |
        sonar-scanner -Dsonar.sources=.
